### ISSUE TITLE
minor pybigtools complaints

### ISSUE THREAD

**Issue by sergpolly** [jackh726/bigtools#28]
pybigtools can feels a bit alien as a python module
would be nice to have access to things like `__version__`,  `__path__` etc etc - e.g. `import pybigtools as pybig; print(pybig.__version__)`

**Comment by ghuls** [comment]
`__path__` is already there:

`__version__` will be there if: https://github.com/jackh726/bigtools/pull/32 gets merged.

```python
In [1]: import pybigtools as pybig

In [2]: print(pybig.__version__)
0.1.4-dev

In [3]: print(pybig.__path__)
['/anaconda3/envs/pybigtools/lib/python3.10/site-packages/pybigtools']
```

**Comment by sergpolly** [comment]
Thank you !
