### ISSUE TITLE
bedToBigBed allow1bpOverlap

### ISSUE THREAD

**Issue by mrvollger** [jackh726/bigtools#49]
Is there an equivalent to the `bedToBigBed` option `-allow1bpOverlap` in `bigtools bedtobigbed`?
```
   -allow1bpOverlap  -- allow exons to overlap by at most one base pair
```
Or is the behavior allowed automatically without needing to set an option? 

Cheers,
Mitchell

**Comment by jackh726** [comment]
My understanding here is that this flag only changes some validation checks that the ucsc bedToBigBed does that bigtools doesn't do. So, it doesn't actually affect the final file.
