### ISSUE TITLE
Issue with resulting .bigwig file and IGV

### ISSUE THREAD

**Issue by maxgmarin** [jackh726/bigtools#55]
Hello,

I am having an issue with the .bigwig file being output using `bigtools bedgraphtobigwig`.

The program will successfully output a `.bw` but when I attempt to visualize the file in IGV I get the following error:
`Unexpected error: newPosition > limit: (27547 > 284)`.

I am attaching the exact command and files I am using below:

```
❯ bigtools --version
bigtools 0.5.2

❯ bigtools bedgraphtobigwig H37Rv.NoSpacesHeader.kmermap.K50_E4.bedgraph H37Rv.NoSpacesHeader.kmermap.K50_E4.chrom.sizes H37Rv.NoSpacesHeader.PileupMap.K50_E4.bw -t 1
```

[H37Rv.NoSpacesHeader.kmermap.K50_E4.chrom.sizes.txt](https://github.com/user-attachments/files/17510346/H37Rv.NoSpacesHeader.kmermap.K50_E4.chrom.sizes.txt)
[H37Rv.NoSpacesHeader.kmermap.K50_E4.bedgraph.txt](https://github.com/user-attachments/files/17510347/H37Rv.NoSpacesHeader.kmermap.K50_E4.bedgraph.txt)

The file persisted when I attempted to output a .bigwig file using the Python API, and with a different .bedgraph file.

I am also attaching similar files for the Lambda phage genome (measuring k-mer mappability). The issue persisted there as well.

[Lambda.J02459.kmermap.K10_E0.bedgraph.txt](https://github.com/user-attachments/files/17510370/Lambda.J02459.kmermap.K10_E0.bedgraph.txt)
[Lambda.J02459.kmermap.K10_E0.chrom.sizes.txt](https://github.com/user-attachments/files/17510371/Lambda.J02459.kmermap.K10_E0.chrom.sizes.txt)
[Lambda.J02459.kmermap.K10_E0.wig.txt](https://github.com/user-attachments/files/17510372/Lambda.J02459.kmermap.K10_E0.wig.txt)

Thank you!
- Max

**Comment by maxgmarin** [comment]
Here is the .bw file that is causing the issue. (I added the `.txt` suffix just to be able to upload it).
Also, I am using `bigtools` and `pybigtools` on macOS (Intel processor).

[H37Rv.NoSpacesHeader.PileupMap.K50_E4.bw.txt](https://github.com/user-attachments/files/17510422/H37Rv.NoSpacesHeader.PileupMap.K50_E4.bw.txt)

**Comment by jackh726** [comment]
Strange! I just downloaded the bigwig you attached, loaded in the H37Rv genome (downloaded from https://www.ncbi.nlm.nih.gov/nuccore/NC_000962.3?report=fasta) and it seems to work for me...

What are you using for your genome? What version of IGV are you using? I think there may be a log at `~/.igv/igv.log`, could you check if that's there and provide any relevant info from that if so?

Really not quite sure what's going on.

**Comment by maxgmarin** [comment]
Hello Jack,

I was using the same genome you downloaded (H37Rv) and I was using IGV 2.17.4. 
I updated my IGV from 2.17.4 to 2.18.4 and the issue was completely resolved .... It must have been some specific issue with my IGV. I will note that IGV (2.17.4) was able to load other .bigwig files without issue, it appeared to be specific to `pybigtools` and `bigtools`.

Thank you for looking into this! I should have updated my IGV version before posting an issue.

For context of how I was using pybigtools, I was writing a simple function to convert a Pandas DF to a .bigwig. 

The function can be found in the [utils.py](https://github.com/maxgmarin/pupmapper/blob/main/pupmapper/utils.py) for a simple command line tool I put together.
```
def pmap_df_to_bigwig(i_Pmap_DF, out_bigwig_path):
    """
    Converts a DataFrame to a BigWig file using the pybigtools library.

    Parameters:
    - i_Pmap_DF: Pandas DataFrame with columns ["chrom", "start", "end", "score"]
    - out_bigwig_path: Path where the output BigWig file will be written
    """
    
    # Step 1: Validate the input DataFrame
    validate_PupMap_DF(i_Pmap_DF)

    # Step 2: Infer chromosome lengths from the DataFrame
    chrom_lengths_dict = infer_ChrLengths(i_Pmap_DF)

    # Step 3: Create the iterable with values (chromosome, start, end, score)
    values_list = ((row["chrom"], row["start"], row["end"], row["score"]) for _, row in i_Pmap_DF.iterrows())

    # Step 4: Open the BigWig file and write the values
    out_BigWig = pybigtools.open(out_bigwig_path, "w")

    out_BigWig.write( chrom_lengths_dict, values_list)
```

Now it works exactly as expected!

- Max
