### ISSUE TITLE
pip install pybigtools leads to BBIReadError (but conda works)

### ISSUE THREAD

**Issue by LukasMahieu** [jackh726/bigtools#64]
Hey, 

I can't reproduce this myself unfortunately but some users of our package which uses pybigtools mention that the pip install leads to errors while the conda install works fine. Any ideas?

https://github.com/aertslab/CREsted/issues/67

**Comment by jackh726** [comment]
Really strange. I'll take a look at this later today.

**Comment by jackh726** [comment]
This issue should be fixed started with pybigtools 0.2.3 that I released today. There was an issue with the sdist to pypi.

Going to go ahead and close - let me know if there are still problems.
